const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const configPath = path.join(__dirname, 'scripts', 'config.js');

console.log('🔄 Loading environment variables from .env...');

let envConfig = {};

if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf-8');
  const lines = envContent.split(/\r?\n/);

  lines.forEach(line => {
    const trimmed = line.trim();
    // Skip empty lines and comments
    if (!trimmed || trimmed.startsWith('#')) return;

    const equalsIdx = trimmed.indexOf('=');
    if (equalsIdx === -1) return;

    const key = trimmed.substring(0, equalsIdx).trim();
    let value = trimmed.substring(equalsIdx + 1).trim();

    // Strip surrounding quotes if any
    if (
      (value.startsWith("'") && value.endsWith("'")) ||
      (value.startsWith('"') && value.endsWith('"'))
    ) {
      value = value.substring(1, value.length - 1);
    }

    envConfig[key] = value;
  });
} else {
  console.warn('⚠️  .env file not found! Generating config.js with placeholder values.');
  envConfig = {
    SUPABASE_URL: 'YOUR_SUPABASE_URL',
    SUPABASE_ANON_KEY: 'YOUR_SUPABASE_ANON_KEY',
    OPENROUTER_KEY: 'YOUR_OPENROUTER_KEY',
    GEMINI_KEY: 'YOUR_GEMINI_KEY',
    YOUTUBE_API_KEY: 'YOUR_YOUTUBE_API_KEY'
  };
}

// Generate the configuration file content
const configContent = `// Global Environment Configuration
// This file is auto-generated by load-env.js from the .env file.
// DO NOT EDIT THIS FILE DIRECTLY AND DO NOT COMMIT IT TO GIT.
window.ENV_CONFIG = {
  SUPABASE_URL: '${envConfig.SUPABASE_URL || ''}',
  SUPABASE_ANON_KEY: '${envConfig.SUPABASE_ANON_KEY || ''}',
  OPENROUTER_KEY: '${envConfig.OPENROUTER_KEY || ''}',
  GEMINI_KEY: '${envConfig.GEMINI_KEY || ''}',
  YOUTUBE_API_KEY: '${envConfig.YOUTUBE_API_KEY || ''}'
};
`;

try {
  fs.writeFileSync(configPath, configContent, 'utf-8');
  console.log('✅ successfully generated scripts/config.js');
} catch (error) {
  console.error('❌ Failed to write scripts/config.js:', error);
  process.exit(1);
}
