const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const configJsPath = path.join(__dirname, 'scripts', 'config.js');
const configJsonPath = path.join(__dirname, 'scripts', 'config.json');

console.log('🔄 Loading environment variables...');

// Start with process.env (system environment variables take priority)
const envConfig = {
  SUPABASE_URL: process.env.SUPABASE_URL || '',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || '',
  OPENROUTER_KEY: process.env.OPENROUTER_KEY || '',
  GEMINI_KEY: process.env.GEMINI_KEY || '',
  YOUTUBE_API_KEY: process.env.YOUTUBE_API_KEY || ''
};

// Fallback to local .env if it exists
if (fs.existsSync(envPath)) {
  console.log('📄 Found local .env file, parsing...');
  const envContent = fs.readFileSync(envPath, 'utf-8');
  const lines = envContent.split(/\r?\n/);

  lines.forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;

    const equalsIdx = trimmed.indexOf('=');
    if (equalsIdx === -1) return;

    const key = trimmed.substring(0, equalsIdx).trim();
    let value = trimmed.substring(equalsIdx + 1).trim();

    // Strip surrounding quotes if any
    if (
      (value.startsWith("'") && value.endsWith("'")) ||
      (value.startsWith('"') && value.endsWith('"'))
    ) {
      value = value.substring(1, value.length - 1);
    }

    // Only set if not already set by system environment (process.env)
    if (!envConfig[key]) {
      envConfig[key] = value;
    }
  });
}

// Generate the configuration javascript content
const configJsContent = `// Global Environment Configuration
// This file is auto-generated by load-env.js.
// DO NOT EDIT THIS FILE DIRECTLY AND DO NOT COMMIT IT TO GIT.
window.ENV_CONFIG = {
  SUPABASE_URL: '${envConfig.SUPABASE_URL || ''}',
  SUPABASE_ANON_KEY: '${envConfig.SUPABASE_ANON_KEY || ''}',
  OPENROUTER_KEY: '${envConfig.OPENROUTER_KEY || ''}',
  GEMINI_KEY: '${envConfig.GEMINI_KEY || ''}',
  YOUTUBE_API_KEY: '${envConfig.YOUTUBE_API_KEY || ''}'
};
`;

// Generate the configuration JSON content
const configJsonContent = JSON.stringify(envConfig, null, 2);

try {
  fs.writeFileSync(configJsPath, configJsContent, 'utf-8');
  console.log('✅ successfully generated scripts/config.js');
  
  fs.writeFileSync(configJsonPath, configJsonContent, 'utf-8');
  console.log('✅ successfully generated scripts/config.json');
} catch (error) {
  console.error('❌ Failed to write configuration files:', error);
  process.exit(1);
}
